---
# Source: minio-resources-operator/templates/service_account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: minio-resource-operator
  labels:
    app: minio-resources-operator
imagePullSecrets: 
  []
---
# Source: minio-resources-operator/templates/cluster_role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: minio-resource-operator
  labels:
    app: minio-resources-operator
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - services/finalizers
      - endpoints
      - persistentvolumeclaims
      - events
      - configmaps
      - secrets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - get
      - create
  - apiGroups:
      - apps
    resourceNames:
      - minio-resources-operator
    resources:
      - deployments/finalizers
    verbs:
      - update
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
  - apiGroups:
      - apps
    resources:
      - replicasets
      - deployments
    verbs:
      - get
  - apiGroups:
      - minio.robotinfra.com
    resources:
      - "*"
      - miniousers
      - miniopolicies
      - miniouserpolicies
      - minioservers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
# Source: minio-resources-operator/templates/cluster_role_binding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: minio-resource-operator
subjects:
  - kind: ServiceAccount
    name: minio-resource-operator
    namespace: default
roleRef:
  kind: ClusterRole
  name: minio-resource-operator
  apiGroup: rbac.authorization.k8s.io
  name: minio-resource-operator
---
# Source: minio-resources-operator/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-resource-operator
  labels:
    app: minio-resources-operator
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: minio-resources-operator
  replicas: 1
  template:
    metadata:
      name: minio-resource-operator
      labels:
        app: minio-resources-operator
    spec:
      serviceAccountName: minio-resource-operator
      containers:
        - name: operator
          image: "robotinfra/minio-resources-operator:v0.3.7"
          imagePullPolicy: IfNotPresent
          command:
            - minio-resources-operator
            - --zap-level
            - debug
          ports:
            - containerPort: 8383
              name: http-metrics
              protocol: TCP
            - containerPort: 8686
              name: cr-metrics
              protocol: TCP
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: minio-resource-operator
          resources: 
            limits:
              memory: 256Mi
            requests:
              cpu: 0.01
              memory: 192Mi
          livenessProbe:
            httpGet:
              path: /metrics
              port: 8383
            initialDelaySeconds: 2
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /metrics
              port: 8383
            initialDelaySeconds: 2
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
