apiVersion: skaffold/v2beta9
kind: Config
metadata:
  name: minio-resources-operator
build:
  artifacts:
  - image: example.com/wb/minio-resource-operator
    context: build
deploy:
  kubectl:
    manifests:
    - deploy.yaml
