---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "minio-operator.fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "minio-operator.name" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ template "minio-operator.fullname" . }}
      release: {{ .Release.Name }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      name: {{ template "minio-operator.fullname" . }}
      labels:
        app: {{ template "minio-operator.fullname" . }}
        release: {{ .Release.Name }}
      annotations: {{ toYaml .Values.podAnnotations | nindent 8 }}
    spec:
      serviceAccountName: {{ template "minio-operator.serviceAccountName" . }}
      containers:
        - name: {{ template "minio-operator.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - minio-resources-operator
          ports:
            - containerPort: 8383
              name: metrics
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: minio-resources-operator
          resources: {{ toYaml .Values.resources | nindent 12 }}
{{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /metrics
              port: 8383
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
{{- end }}
{{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /metrics
              port: 8383
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
{{- end }}
{{- if .Values.nodeSelector }}
        nodeSelector: {{ toYaml .Values.nodeSelector | nindent 10 }}
{{- end }}
{{- if .Values.securityContext }}
        securityContext: {{ toYaml .Values.securityContext | nindent 10 }}
{{- end }}
{{- if .Values.tolerations }}
        tolerations: {{ toYaml .Values.tolerations | nindent 10 }}
{{- end }}
