{{- if .Values.serviceMonitor.enabled }}
{{- $fullname := include "minio-operator.fullname" . -}}
{{- $name := include "minio-operator.name" . }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ $name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name | quote }}
  name: {{ $fullname }}
spec:
  endpoints:
    - port: http-metrics
    - port: cr-metrics
  jobLabel: {{ $name }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: {{ $name }}
      release: {{ .Release.Name | quote }}
{{- end }}
