{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "minio-operator.name" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- if .Values.serviceMonitor.labels }}
{{ toYaml .Values.serviceMonitor.labels | indent 4}}
{{- end }}
  name: {{ template "minio-operator.fullname" . }}-prometheus-exporter
{{- if .Values.serviceMonitor.namespace }}
  namespace: {{ .Values.serviceMonitor.namespace }}
{{- end }}
spec:
  endpoints:
    - port: metrics
      path: /metrics
{{- if .Values.serviceMonitor.interval }}
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
  jobLabel: {{ template "minio-operator.fullname" . }}-prometheus-exporter
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: {{ template "minio-operator.name" . }}
      release: {{ .Release.Name | quote }}
{{- end }}
