apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: minioservers.minio.robotinfra.com
spec:
  group: minio.robotinfra.com
  names:
    kind: MinioServer
    listKind: MinioServerList
    plural: minioservers
    singular: minioserver
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: MinioServer is the Schema for the minioservers API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: MinioServerSpec defines the desired state of MinioServer
          properties:
            accessKey:
              type: string
            hostname:
              type: string
            port:
              type: integer
            secretKey:
              type: string
            ssl:
              type: boolean
          required:
          - accessKey
          - hostname
          - port
          - secretKey
          type: object
        status:
          description: MinioServerStatus defines the observed state of MinioServer
          properties:
            online:
              type: boolean
          required:
          - online
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
