apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: miniousers.minio.walkbase.com
spec:
  group: minio.walkbase.com
  names:
    kind: MinioUser
    listKind: MinioUserList
    plural: miniousers
    singular: miniouser
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: MinioUser is the Schema for the miniousers API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: MinioUserSpec defines the desired state of MinioUser
          properties:
            policy:
              type: string
            server:
              type: string
          required:
          - server
          type: object
        status:
          description: MinioUserStatus defines the observed state of MinioUser
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
