---
version: "3.6"

volumes:
  minio:
    name: minio-operator

services:
  minio:
    image: minio/minio:RELEASE.2020-01-16T22-40-29Z
    hostname: minio-operator-minio
    container_name: minio-operator-minio
    restart: unless-stopped
    environment:
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: testtest
    volumes:
      - minio:/export
    command: server /export
  go:
    container_name: minio-operator
    hostname: minio-operator
    restart: unless-stopped
    build: .
    volumes:
      - ../:/workspace
      - ~/.ssh:/root/.ssh:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: /bin/sleep 99999h
    environment:
      # for mc
      MC_HOST_test: http://admin:testtest@minio:9000
      # for operator
      MINIO_SSL: "false"
      MINIO_PORT: "9000"
      MINIO_HOSTNAME: minio
      MINIO_ACCESSKEY: admin
      MINIO_SECRETKEY: testtest