apiVersion: minio.robotinfra.com/v1alpha1
kind: MinioUser
metadata:
  name: example-miniouser
spec:
  server: dev-minioserver
  accessKey: myUsername
  secretKey: mySecurePassword
  policy: |
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Action": [
            "s3:*"
          ],
          "Effect": "Allow",
          "Resource": [
            "arn:aws:s3:::mybucket/*",
            "arn:aws:s3:::mybucket"
          ],
          "Sid": ""
        }
      ]
    }
